networks:
  discourse:
    external: true

services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:14.0.0@sha256:01b82c6c1c64d5b73ba161c0107e5d7d038ebdce85eb9ed084f043e9c2a7943b
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: cups-g11.aosus.org
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      # - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      # - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      # - "993:993"  # IMAP4 (implicit TLS)
      # - "110:110"  # POP3
      - "995:995"  # POP3 (with TLS)
    volumes:
      - mail-data:/var/mail
      - mail-state:/var/mail-state
      - mail-logs:/var/log/mail
      - config:/tmp/docker-mailserver
      - /etc/localtime:/etc/localtime:ro
      - type: volume
        source: caddy_data
        target: /etc/letsencrypt/live/cups-g11.aosus.org/fullchain.pem
        volume:
          nocopy: true
          subpath: caddy/certificates/acme-v02.api.letsencrypt.org-directory/cups-g11.aosus.org/cups-g11.aosus.org.crt
      - type: volume
        source: caddy_data
        target: /etc/letsencrypt/live/cups-g11.aosus.org/privkey.pem
        volume:
          nocopy: true
          subpath: caddy/certificates/acme-v02.api.letsencrypt.org-directory/cups-g11.aosus.org/cups-g11.aosus.org.key
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    networks:
      discourse:

volumes:
  mail-data:
  mail-state:
  mail-logs:
  config:
  caddy_data:
    external: true